# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
    identifier = "github"
    name       = "GitHub"
    url        = "https://github.com/0xAshhh"

    [social.params]
        icon = "brand-github"

[[social]]
    identifier = "instagram"
    name       = "Instagram"
    url        = "https://www.instagram.com/71__anas/"

    [social.params]
        icon = "brand-instagram"

[[social]]
    identifier = "linkedin"
    name       = "LinkedIn"
    url        = "https://www.linkedin.com/in/anas-almashaileh-ba443a395/?skipRedirect=true"

    [social.params]
        icon = "brand-linkedin"
